
CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(45) NOT NULL,
    Age VARCHAR(3) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    Address VARCHAR(45) NOT NULL,
    Image BLOB,
    Status ENUM('ACTIVE', 'INACTIVE'),
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL
);

CREATE TABLE Permissions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(45) NOT NULL,
    GuardName VARCHAR(45) NOT NULL,
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    Description TEXT,
    Module VARCHAR(45) NOT NULL
);

CREATE TABLE Roles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(45) NOT NULL,
    GuardName VARCHAR(45) NOT NULL,
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    Description TEXT
);

CREATE TABLE Educations (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Institution VARCHAR(255),
    Title VARCHAR(255),
    StartDate DATE,
    EndDate DATE,
    Description TEXT,
    Status ENUM('ACTIVE', 'INACTIVE'),
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE ExtraCourses (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Course VARCHAR(255),
    Institution VARCHAR(255),
    StartDate DATE,
    EndDate DATE,
    Description TEXT,
    Status ENUM('ACTIVE', 'INACTIVE'),
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE SocialLogins (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Provider VARCHAR(255),
    ProviderId VARCHAR(255),
    CreateAt DATETIME,
    UpdateAt DATETIME,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE RolePermissions (
    PermissionId INT,
    RoleId INT,
    FOREIGN KEY (PermissionId) REFERENCES Permissions(Id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE Skills (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    SkillName VARCHAR(255),
    ProficiencyLevel VARCHAR(255),
    Status ENUM('ACTIVE', 'INACTIVE'),
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE UserPermissions (
    PermissionId INT,
    UserType VARCHAR(45),
    UserId INT,
    FOREIGN KEY (PermissionId) REFERENCES Permissions(Id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE UserRoles (
    RoleId INT,
    UserType VARCHAR(45),
    UserId INT,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE WorkHistories (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Company VARCHAR(255),
    Position VARCHAR(255),
    StartDate DATE,
    EndDate DATE,
    Description TEXT,
    Status ENUM('ACTIVE', 'INACTIVE'),
    CreateAt DATETIME NOT NULL,
    UpdateAt DATETIME NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
